<?php
/**
 * @file
 * Install, update, and uninstall functions for the adyax_test module.
 */

/**
 * Implements hook_field_schema.
 */
function adyax_test_field_schema($field) {
  $columns = array(
    'vimeo_code' => array('type' => 'int', 'not null' => FALSE),
    'fid' => array('type' => 'int', 'not null' => FALSE),
  );
  $indexes = array(
    'vimeo_code' => array('vimeo_code'),
  );
  return array(
    'columns' => $columns,
    'indexes' => $indexes,
  );
}
